### ISSUE TITLE
menos mensajes

### ISSUE THREAD

**Issue by erseco** [jesusgn90/etsiit-moderator#11]
el bot debería dar menos mensajes, de hecho no es muy util el mensaje de que te ha añadadido a la base de datos, o el de "cuentame más", quizá podría enviar esos mensajes al usuario en cuestión por privado

**Comment by jesusgn90** [comment]
Se ha creado una encuesta rápida, para saber si la gente piensa que habla demasiado y para saber que les gustaría añadirle, https://goo.gl/forms/oIGvtYyv5D9qk1Ug1, en función de eso vemos :+1:

**Comment by jesusgn90** [comment]
Solucionado
