### ISSUE TITLE
Fallo aviso/perdona sin ser admin

### ISSUE THREAD

**Issue by ainokila** [jesusgn90/etsiit-moderator#20]
Puedes crear un grupo en el que seas tu el admin, añades al bot y puedes perdonar y avisar a quien quieras.

Esto creo que es debido a que los almacenas tal cual en la bbdd de mongo, pero deberias añadirle el id de grupo, para que no se pueda hacer eso desde otro grupo,

**Comment by jesusgn90** [comment]
Vale ahora si entiendo lo que comentas, ok !

**Comment by jesusgn90** [comment]
Fixed
