### ISSUE TITLE
Aviso al usar lenguaje "no correcto"

### ISSUE THREAD

**Issue by ado07** [jesusgn90/etsiit-moderator#6]
Esta funcionalidad permitiría advertir a un usuario incrementando el número de avisos en 1 si escribe X veces palabras a evitar en un tiempo Y. Con esto si un usuario se salta las advertencias del bot sobre lenguaje mal sonante de forma deliberada, no seria necesaria la acción de aviso por parte de un administrador.

**Comment by jesusgn90** [comment]
Interesante eso puede implementarse relativamente rápido gracias

**Comment by jesusgn90** [comment]
Fijado que aumente 0.10 avisos por palabra incorrecta. [https://github.com/jesusgn90/etsiit-moderator/commit/e077e30f8d52e90f15a9053ddf053422d76d7fb1](https://github.com/jesusgn90/etsiit-moderator/commit/e077e30f8d52e90f15a9053ddf053422d76d7fb1)
